<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kode Voucher ( bila ada )_code_voucher</name>
   <tag></tag>
   <elementGuidId>b666dc41-1a17-491a-80b9-dd7647d375ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='code_voucher']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;code_voucher&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21b56326-d19e-4d17-9ff1-a411b27235e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44a92025-d983-42d8-8e66-8b11f7c87027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control empty</value>
      <webElementGuid>8b233d56-a529-43ac-86fb-7df833ca5b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code_voucher</value>
      <webElementGuid>4cb36973-1672-4d6a-baae-fe6619c5e5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;code_voucher&quot;)/input[@class=&quot;form-control empty&quot;]</value>
      <webElementGuid>18a6a9a5-203c-4f44-96a0-38ef09f7a394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='code_voucher']</value>
      <webElementGuid>9aa3f13c-5659-4c17-97b6-3fb361d43731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='code_voucher']/input</value>
      <webElementGuid>27050a61-4e18-499d-9df2-d27e3987b5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>7fd0ba05-752f-4d52-9371-80caa697e6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code_voucher']</value>
      <webElementGuid>5fdbd55e-5840-4c57-8e06-b7ed8d7b2ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
