<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>contact-instagram</name>
   <tag></tag>
   <elementGuidId>ebdd39f6-31e0-414c-9a6b-935254da9cce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='instagram sistemtoko.com']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;instagram sistemtoko.com&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dafd8fba-28bc-41bd-9294-261d40e3fe16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://sistemtoko.com/assets/landing-page-new/assets/images/sosmed-instagram.png</value>
      <webElementGuid>359774dd-0c4b-4fa4-ab6c-410d866be74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>instagram sistemtoko.com</value>
      <webElementGuid>bd3080e6-4b48-4aec-8e9b-37d3d3b5c8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;siskofrontend&quot;]/aside[@class=&quot;socialmedia&quot;]/div[@class=&quot;image-sosmed&quot;]/a[1]/img[1]</value>
      <webElementGuid>90d48047-cd35-4900-965f-b12369a58091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='instagram sistemtoko.com']</value>
      <webElementGuid>a592721a-d272-4d75-b0a4-4394a20def94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>8f75a03a-ffce-436e-bcc9-4cfee8381e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://sistemtoko.com/assets/landing-page-new/assets/images/sosmed-instagram.png' and @alt = 'instagram sistemtoko.com']</value>
      <webElementGuid>6a55d8c6-be6c-4ac7-963d-893457e40575</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
