<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>jenis-usaha</name>
   <tag></tag>
   <elementGuidId>9283a163-b11c-4154-8099-94f466c65dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='penjelasan-1']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-12 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb471d86-1767-4c28-a34e-26c6ecc96707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dapat digunakan untuk berbagai jenis usaha</value>
      <webElementGuid>3b27456d-aceb-42ed-9603-7d28490e74df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penjelasan-1&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]</value>
      <webElementGuid>1559d79e-cbcd-4055-932c-59fa8dbbc90d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='penjelasan-1']/div/div/div</value>
      <webElementGuid>2f4c7c25-105a-4ba5-99ed-f8f7f0dd8776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tim Marketing'])[1]/following::div[4]</value>
      <webElementGuid>b6edd2fe-3b1d-41e7-a541-b8c04c10120c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan Gratis'])[1]/following::div[10]</value>
      <webElementGuid>00121fe7-6efe-4305-8ae5-8a483d092fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko Online'])[1]/preceding::div[2]</value>
      <webElementGuid>f6a12dd1-5442-43e4-8254-5e1f5b09a3e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko Offline'])[1]/preceding::div[3]</value>
      <webElementGuid>4987a099-7d91-474b-8b67-4656b2080092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dapat digunakan untuk berbagai jenis usaha']/parent::*</value>
      <webElementGuid>d93146cd-23da-44b6-86be-1a9972bcc9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div</value>
      <webElementGuid>2b34debc-ee12-47b8-aee0-d2a0922b098d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dapat digunakan untuk berbagai jenis usaha' or . = 'Dapat digunakan untuk berbagai jenis usaha')]</value>
      <webElementGuid>ed6c5fdc-858c-499d-960b-2ef1216ce4ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
